### ISSUE TITLE
Unable to activate

### ISSUE THREAD

**Issue by GoldenAdrien** [ItsCubeTime/FastPBR#1]
so whenever I check the box to activate it, I get this issue:
<img width="647" alt="Screen Shot 2022-01-27 at 1 23 11 AM" src="https://user-images.githubusercontent.com/42684395/151330462-7d4040e3-313b-45a0-85d0-9d76b9da7983.png">

**Comment by ItsCubeTime** [comment]
Interesting, Im sorry to say it but I do not support any other OS than Windows at the moment as my focus have been to just slam in as many features in the addon as absolutely possible.

For anyone reading this, I am however interested if any other contributor would be willing to help me port the addon to work on other operative systems (like mac or Linux) as well! I believe the code base should be somewhat easy to modify to work on any OS for someone thats working on mac/Linux.

**Comment by ItsCubeTime** [comment]
If you see this error message on a Windows device however, lemme know!
